baseURL = "//martachupil.github.io/"
languageCode = "en-us"
title = "Marta Chupil"
theme = "aether"
author = "Marta Chupil"
disableKinds = "RSS"
canonifyurls = true
paginate = 3

[params]
brand = "Marta Chupil"
description = "The website's description"
# homeimg = "URL to the image used for the home button at the bottom of each post - optional"
# bgimg = "URL to the image used for the page background - optional"
rssinmenu = false
bgimg = "img/ignasi_pattern_s.png"